# Generated by Django 4.0.3 on 2024-04-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_polity_alternate_religion_family_alternate_religion_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polity_language',
            name='colour',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
