# Generated by Django 4.0.3 on 2024-04-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_polity_alternate_religion_private_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polity_preceding_entity',
            name='merged_old_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
