# Generated by Django 4.0.3 on 2023-11-02 11:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_polity_general_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacrostateShapefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=50, null=True)),
                ('polity', models.CharField(max_length=50, null=True)),
                ('date_from', models.CharField(max_length=50, null=True)),
                ('date_to', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
