# Generated by Django 4.0.3 on 2023-12-08 10:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_gadmprovinces'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoShapefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=100)),
                ('name_underscores', models.CharField(max_length=100)),
                ('wikipedia_name', models.CharField(max_length=100, null=True)),
                ('seshat_id', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(null=True)),
            ],
        ),
    ]
