# Generated by Django 4.0.3 on 2024-02-21 13:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_gadmcountries_gadmprovinces_gadmshapefile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoShapefileLowRes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=100)),
                ('polity', models.CharField(max_length=100)),
                ('wikipedia_name', models.CharField(max_length=100, null=True)),
                ('seshat_id', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('polity_start_year', models.IntegerField()),
                ('polity_end_year', models.IntegerField()),
                ('colour', models.CharField(max_length=7)),
            ],
        ),
    ]
