# Generated by Django 4.0.3 on 2024-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_polity_shapefile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='alternative_names',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
