# Generated by Django 4.0.3 on 2024-04-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_videoshapefile_simplified_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadmprovinces',
            name='COUNTRY',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
