# Generated by Django 4.0.3 on 2024-04-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_gadmprovinces_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoshapefile',
            name='language',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videoshapefile',
            name='language_colour',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
