# Generated by Django 4.0.3 on 2024-04-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_videoshapefile_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoshapefile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='videoshapefile',
            name='language_colour',
        ),
    ]
