# Generated by Django 4.0.3 on 2024-05-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_gadmcountries_gadmprovinces_gadmshapefile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoshapefile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
