# Generated by Django 4.0.3 on 2024-04-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_seshatprivatecomment_seshatprivatecommentpart'),
        ('rt', '0007_alter_elites_religion_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elites_religion',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gov_dis_rel_grp_occ_fun',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gov_obl_rel_grp_ofc_reco',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gov_press_conv',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gov_press_conv_for_aga',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gov_res_cir_rel_lit',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gov_res_cons_rel_buil',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gov_res_conv',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gov_res_prop_own_for_rel_grp',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gov_res_pub_pros',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gov_res_pub_wor',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gov_res_rel_edu',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gov_vio_freq_rel_grp',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='official_religion',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='religious_fragmentation',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='soc_dis_rel_grp_occ_fun',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='soc_vio_freq_rel_grp',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='sync_rel_pra_ind_beli',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='tax_rel_adh_act_ins',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='theo_sync_dif_rel',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='widespread_religion',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
    ]
