# Generated by Django 4.0.3 on 2024-04-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_seshatprivatecomment_seshatprivatecommentpart'),
        ('crisisdb', '0065_alter_agricultural_population_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultural_population',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='arable_land',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='arable_land_per_farmer',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='crisis_consequence',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='crop_failure_event',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='disease_outbreak',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='drought_event',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='external_conflict',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='external_conflict_side',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='famine_event',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gdp_per_capita',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='gross_grain_shared_per_agricultural_population',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='human_sacrifice',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='internal_conflict',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='locust_event',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='military_expense',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='net_grain_shared_per_agricultural_population',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='power_transition',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='silver_inflow',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='silver_stock',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='socioeconomic_turmoil_event',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='surplus',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
        migrations.AddField(
            model_name='total_population',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
    ]
